name: Run Affordability Analysis Script

on:
  workflow_dispatch:  # Enable manual trigger
  schedule:
    # Run the job on the 13th of every month at 00:00 UTC
    - cron: '0 0 13 * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Ensure your dependencies are listed in this file

    - name: Run the Python Script
      run: |
        python greaffordabilitygap.py  # Ensure you use 'python' to run the script

- name: Force Commit Updated CSV to Private Repository
  run: |
    git config --global user.name "github-actions[bot]"
    git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
    git add -f c_income_zhvi_mortgage_comprehensive_affordability.csv  # -f forces the file to be added
    git commit --allow-empty -m "Force update affordability analysis on 13th of the month"  # --allow-empty ensures commit even if no changes
    git push origin main  # Push the commit to the remote repository
